### ISSUE TITLE
Linguistic modifiers missed

### ISSUE THREAD

**Issue by mecst76** [dbmi-pitt/nobletools#17]
There is a negation term and probable existence term in the same sentence. However, concepts within the sentence are assigned the default linguistic modifier values.

"If pathology on the right 9:30 specimens is NOT DCIS or invasive cancer," - DCIS and invasive cancer are assigned the default modifiers instead of having DefiniteNegatedExistence or ProbableExistence.

**Comment by tseytlin** [comment]
There are two issues here:
1) The sentence is broken into two sentences right before NOT". I will investigate why this is happening.
2) NOT is not being detected by NC. The reason is that NC uses the following heuristic to handle possible acronyms:
// if matched term is a single word && likely abbreviation && rest of text is not uppercase
Basically because the sentence is mixed case, NOT in text is upper cases and hence NC thinks it is an abbreviation of some sort and 'not' in modifier ontology doesn't have NOT as a synonym for case sensitive match, NC scores the weight of this match below threshold of usable.

I can either disable scoring of concepts for matching modifiers altogether to avoid this issue or we can add NOT as a synonym to 'not' modifier. 

What do you think?

**Comment by tseytlin** [comment]
The sentence was broken because in the actual document the line "If pathology on the right 9:30 specimens is " is on a separate line from "NOT DCIS or invasive cancer,"

Because the start of the second line is all upper case, the sentence parser thinks it is not a Prose sentence.
